name: Lint Unity Code

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and Activate Unity
        uses: game-ci/unity-activate@v2.0.0
        with:
          version: '2021.3.15f1'
          install-location: '/opt/unity'
          unity-license-file: $UNITY_LICENSE
      - name: Set environment variables
        env:
          ANALYSER_CONFIG_FILE: .github/workflows/unity-analyzer.json
      - name: Run Unity Analyzer
        run: |
          Unity -batchmode -nographics -projectPath "${GITHUB_WORKSPACE}" -executeMethod UnityEditor.UnityAnalyzer.Analyze -analyzerConfigFile "${ANALYSER_CONFIG_FILE}"
